### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by travishen** [FroggyTaipei/froggy-service#18]
### npm install的錯誤訊息
```
$ npm install
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none was installed.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none was installed.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-node@>=7.0.0 but none was installed.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-promise@>=4.0.0 but none was installed.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-standard@>=4.0.0 but none was installed.
npm WARN pug-plain-loader@1.0.0 requires a peer of pug@^2.0.0 but none was installed.
```
### docker-compose的錯誤訊息
```
$ docker-compose up -f docker-compose-prod.yml --build
```
```
Building nginx
Step 1/11 : FROM node:10-alpine as build-deps
 ---> 288d2f688643
Step 2/11 : WORKDIR /app/
 ---> Using cache
 ---> cab64f2fa0b0
Step 3/11 : COPY frontend/package.json frontend/package-lock.json /app/
 ---> Using cache
 ---> 69d6843c51cc
Step 4/11 : RUN npm install
 ---> Using cache
 ---> 327034b15b5a
Step 5/11 : COPY frontend /app/
 ---> bf4233759146
Step 6/11 : COPY .env /app/.env
 ---> c2712b6ffb27
Step 7/11 : RUN npm run build
 ---> Running in 3674a4732be6

> frontend@0.1.0 build /app
> vue-cli-service build


 ERROR  Failed to compile with 5 errors4:30:41 PM

 error  in ./src/components/Navbar.vue?vue&type=template&id=c024b5b6&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/pug-plain-loader/index.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./src/components/Navbar.vue?vue&type=template&id=c024b5b6&lang=pug& 1:0-434 1:0-434
 @ ./src/components/Navbar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/Dialogue.vue?vue&type=template&id=47ddf776&scoped=true&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/pug-plain-loader/index.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./src/components/Dialogue.vue?vue&type=template&id=47ddf776&scoped=true&lang=pug& 1:0-448 1:0-448
 @ ./src/components/Dialogue.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/CaseList.vue?vue&type=template&id=ec853584&scoped=true&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/pug-plain-loader/index.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./src/components/CaseList.vue?vue&type=template&id=ec853584&scoped=true&lang=pug& 1:0-448 1:0-448
 @ ./src/components/CaseList.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/About.vue?vue&type=template&id=26463892&scoped=true&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/pug-plain-loader/index.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./src/components/About.vue?vue&type=template&id=26463892&scoped=true&lang=pug& 1:0-445 1:0-445
 @ ./src/components/About.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/Footer.vue?vue&type=template&id=66e0fd9e&scoped=true&lang=pug&

Module build failed (from ./node_modules/pug-plain-loader/index.js):
Error: Cannot find module 'pug'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/node_modules/pug-plain-loader/index.js:1:75)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at loadLoader (/app/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /app/node_modules/loader-runner/lib/LoaderRunner.js:173:18

 @ ./src/components/Footer.vue?vue&type=template&id=66e0fd9e&scoped=true&lang=pug& 1:0-446 1:0-446
 @ ./src/components/Footer.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by travishen** [comment]
#11 Win10 Pro環境執行docker-compose失敗

**Comment by travishen** [comment]
#19

**Comment by travishen** [comment]
#19 之後可以完成build，其中還有幾個相依性的警告：
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by ankycheng** [comment]
fsevents 似乎只在 OS X 系統上需要，linux 及 windows 忽略即可
Ref: https://www.reddit.com/r/node/comments/93bcrx/using_nodeenv_to_install_parcel_but_it_skips/
